services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ang-backend
    ports:
      - "9090:9090"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_INIT_PASSWORD: ${ADMIN_INIT_PASSWORD}
      FILE_UPLOAD_DIR: /app/uploads
      AI_BASE_URL: http://ai:8888
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ang-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend

  ai:
    build:
      context: ./AI
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ang-ai
    ports:
      - "8888:8888"
    environment:
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_HOST: ${OLLAMA_BASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploads:/app/uploads
