name: CD Deploy

on:
  push:
    branches:
      - dev-server
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}

          script: |
            set -e

            echo "===== ANG CD START ====="
            echo "BRANCH: ${{ github.ref_name }}"

            cd "${{ secrets.DEPLOY_PATH }}"

            echo "===== CURRENT PATH ====="
            pwd

            echo "===== GIT UPDATE ====="
            git fetch origin
            git checkout "${{ github.ref_name }}"
            git reset --hard "origin/${{ github.ref_name }}"

            echo "===== DOCKER DOWN ====="
            docker compose down

            echo "===== DOCKER BUILD ====="
            docker compose up -d --build

            echo "===== CLEAN UNUSED IMAGES ====="
            docker image prune -f

            echo "===== DEPLOY COMPLETE ====="