name: CD Deploy

on:
  push:
    branches:
      - dev-server
      - dev
      - test-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}

            git fetch origin
            git checkout dev-server
            git pull origin dev-server

            docker compose down
            docker compose up -d --build

            docker image prune -f